

name: "Build Dark Ages kernel on darky."              # Description of the workflow.
on:
  push:
    branches: darky                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build Dark Ages kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: ock332/android_kernel_xiaomi_sm8350        # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: Android Kernel Action
      uses: lemniskett/android-kernel-actions@v1.0.0

      with:
        arch: arm64                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
        defconfig: vince_defconfig                    # Specify defconfig to use
        image: Image.gz-dtb                           # Specify final build file
